version: 2

jobs:
  setup:
    docker:
    - image: circleci/node:10.11.0

    working_directory: ~/project

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}

        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules

        key: v1-dependencies-{{ checksum "package.json" }}

  lint-and-test:
    docker:
    - image: circleci/node:10.11.0

    working_directory: ~/project

    steps:
    - run:
        name: Linting
        command: npm run lint

  build:
    docker:
    - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
    - run:
        name: Building
        command: npm run build

  deploy-staging:
    docker:
    - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
    - run:
        name: Linting
        command: npm run lint

  deploy-production:
    docker:
    - image: circleci/node:10.11.0

    working_directory: ~/repo

    steps:
    - run:
        name: Linting
        command: npm run lint

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
              - gh-pages

      - lint-and-test:
          requires:
          - setup

      - build:
          requires:
          - lint-and-test
          filters:
            branches:
              only:
              - master
              - staging

      - deploy-staging:
          requires:
          - build
          filters:
            branches:
              only:
              - staging

      - deploy-production:
          requires:
          - build
          filters:
            branches:
              only:
              - master
