version: 2

references:
  container_config: &container_config
    docker:
    - image: circleci/node:10.13.0

    working_directory: ~/project

jobs:
  lint-and-test:
    <<: *container_config

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - node-dependencies-{{ checksum "package.json" }}

        # fallback to using the latest cache if no exact match is found
        - node-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules

        key: node-dependencies-{{ checksum "package.json" }}

    - run:
        name: Linting
        command: npm run lint

  build:
    <<: *container_config

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - node-dependencies-{{ checksum "package.json" }}

        # fallback to using the latest cache if no exact match is found
        - node-dependencies-

    - run: yarn install

    - save_cache:
        paths:
        - node_modules

        key: node-dependencies-{{ checksum "package.json" }}

    - run:
        name: Building
        command: npm run build

    - persist_to_workspace:
        root: ~/repo/dist
        paths:
          - dist/*

  deploy-staging:
    docker:
    - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
    - attach_workspace:
        at: ~/repo/dist

  deploy-production:
    docker:
    - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
    - attach_workspace:
        at: ~/repo/dist

workflows:
  version: 2

  lint-and-test:
    jobs:
      - lint-and-test:
          filters:
            branches:
              ignore:
              - gh-pages

  build-and-deploy:
    jobs:
      - lint-and-test:
          filters:
            branches:
              only:
              - master
              - staging

      - build:
          requires:
          - lint-and-test

      - deploy-staging:
          requires:
          - build
          filters:
            branches:
              only:
              - staging

      - deploy-production:
          requires:
          - build
          filters:
            branches:
              only:
              - master
